# Numpy (numerical python)

NumPy is a library that has ndarray(array object in NumPy) as its basic data structure used to handle arrays and matrices. 

 In python there are list that can operate as numpy but list are slow in process therefore numpy helps in solving the problem since NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [3]:
# convention for importing numpy
import numpy as np #np is an alias used for refering numpy
arr = [6,2,8,9,5,1]
print(type(arr))

<class 'list'>


### Creating an array

We create a NumPy ndarray object using the array() fn

In [2]:
a = np.array(arr)
print(type(a))
print(a.shape)# a is a 1d array with 6 items
print(a.dtype)
print(a.ndim)# get the dimension of a with ndim

<class 'numpy.ndarray'>
(6,)
int32
1


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)# b is a 2d array with 2 rows and 3 cols

[[1 2 3]
 [4 5 6]]
2
(2, 3)


One dimensional array, is an array that has 0-D arrays as its elements

Two dimensional array, An array that has 1-D arrays as its elements

Three dimensional array, is An array that has 2-D arrays as its elements

There are many operations that takes place in numpy arrays which include

1. numpy array indexing
2. numpy array slicing
3. numpy array shape
4. numpy array reshape
5. numpy array split
6. numpy array join

In [4]:
dir(b)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

There are also some inbuilt fns that can be used to initialize numpy which include 
empty[]
zeros[]
ones[]
full[]
random.random[]

In [8]:
# a 2*3 array with random values
print(np.random.random((2,3)))

# a 2*3 array of zeros
print(np.zeros((2,3)))

# a 2*3 array of ones
print(np.ones((2,3)))

# a 3*3 identity matrix
print(np.identity(3))

[[0.74820711 0.93699275 0.24026288]
 [0.12671747 0.94380445 0.67429352]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Intra-operability of Arrays and Scalars
Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. This allows for batch arithmetic operations on the arrays by applying the operator elementwise. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1

In [11]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])

d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

print('Addition:', c+d)
print('Multiplication:', c*d)
print('Division:', 5/d)
print('Sqr:', c**2)

Addition: [[13. 13. 13.]
 [10. 10. 10.]]
Multiplication: [[36. 40. 42.]
 [ 9. 16. 21.]]
Division: [[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
Sqr: [[81. 64. 49.]
 [ 1.  4.  9.]]


### Indexing With Arrays & Using Arrays for Data Processing
The elements in the example arrays above can be accessed by indexing like lists in Python such that

In [22]:
a[0] #= 6
a[3] #= 9
print(a)
b[0, 0] #= 1
b[1, 2] #= 6
print(b)
c[0, 1] #= 8
print(c)

[6 2 8 9 5 1]
[[1 2 3]
 [4 5 6]]
[[9. 8. 7.]
 [1. 2. 3.]]


Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing

In [4]:
# print(d[0:2, :2]) #= array([9., 8.])
e = np.array([[10, 11, 12], [13, 14, 15]
             ,[16, 17, 18], [19, 20, 21]])

# slicing
print(e[:3, 1:])

[[11 12]
 [14 15]
 [17 18]]


In [13]:
y = np.array([10, 20, 30, 40, 50, 60])
print(y[1:4])

[20 30 40]


#### Note

The result includes the start index, but excludes the end index

In [34]:
#advanced methods of indexing
# integer indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]], 

(array([18, 11, 19, 15]),)

In [36]:
#boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

Numpy also has inbuilt mathematical functions like sum(), mean(), std(), corrcoef(), min() and others.

Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().

### NumPy reshape

Reshaping can be adding or removing number of elements in each dimension

In [14]:
#reshaping from 1-D to 2-D
z = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])
new_z = z.reshape(4, 3)
print(new_z)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [16]:
# reshaping 1-D to 3-D
new_zy = z.reshape(2, 3, 2)
print(new_zy)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


### NumPy joining array

In [21]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

arr1 = np.concatenate((x, y))
print(arr1)

[10 20 30 40 50 60]


we can join array using slack fns such as vstack which stacks along the column.

In [22]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

arr2 = np.vstack((x, y))
print(arr2)

[[10 20 30]
 [40 50 60]]


### NumPy splitting array

In [23]:
#use array_split() fn argument=(array to be split, the number of split)
arr3 = np.array_split(z, 3)
print(arr3)

[array([2, 4, 6, 8]), array([10, 12, 14, 16]), array([18, 20, 22, 24])]
